site_name: Interactive Handout

theme:
  feature:
    tabs: true
  name: material

docs_dir: content
site_dir: docs

site_url: https://insper-education.github.io/interactive-handout/
repo_name: "Interactive Handout"
repo_url: https://github.com/insper-education/interactive-handout
edit_uri: edit/main/content/

nav:
  - Home: index.md
  - Reference:
      - reference/basic-editing/index.md
      - reference/advanced-editing/index.md
      - reference/slides/index.md
      - reference/quiz/index.md
      - reference/short-questions/index.md
      - reference/progress-check/index.md

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.0.0/js-yaml.min.js
  - https://unpkg.com/react@17/umd/react.production.min.js
  - https://unpkg.com/react-dom@17/umd/react-dom.production.min.js
  - https://unpkg.com/prop-types@15.6/prop-types.min.js
  - https://unpkg.com/react-is@16.8.3/umd/react-is.production.min.js
  - https://unpkg.com/styled-components/dist/styled-components.min.js
  - js/markdown-enhancer.js

markdown_extensions:
  - markdown.extensions.admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - attr_list

plugins:
  - git-revision-date-localized
